export const trackedPairs = [
  "BTCUSDT","ETHUSDT","XRPUSDT","SOLUSDT","ADAUSDT","DOTUSDT","LTCUSDT","LINKUSDT","AVAXUSDT",
  "ATOMUSDT","MATICUSDT","ARBUSDT","NEARUSDT","OPUSDT","INJUSDT","APTUSDT","AAVEUSDT","ETCUSDT","FILUSDT","HBARUSDT",
  "EGLDUSDT","STXUSDT","XLMUSDT","TONUSDT","ALGOUSDT","RUNEUSDT","SUIUSDT","FLOWUSDT","DYDXUSDT"];
